### ISSUE TITLE
Build latest version (1.2.0)

### ISSUE THREAD

**Issue by domdfcoding** [conda-forge/sphinx-prompt-feedstock#1]
Hi,

Would it be possible to have version 1.2.0 on conda-forge? I believe the only change from version 1.1.0 was to enable parallel Sphinx builds, so I think the existing recipe should still work. 

Thanks 😀

**Comment by jonathansick** [comment]
We've just merged #2 which should give you sphinx-prompt 1.3.0. Cheers.
